---
title: "Ocupação de UTIs"
description: |
  Ocupação de leitos de UTI em Porto Alegre
author:
  - name: Márcio Rodrigues 
    url: https://example.com/norajones
    affiliation: Secretaria Municipal de Saúde
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Bibliotecas -------------------------------------------------------------
library(pacman)

# Georreferenciamento e mapas
p_load(ggmap)
p_load(sp)
p_load(rgdal)
p_load(hereR)
p_load(geobr)

# Tabelas, Ferramentas estatísticas,
p_load(directlabels)
p_load(esquisse)
p_load(obAnalytics)
p_load(DescTools)
p_load(kableExtra)
p_load(RColorBrewer)
p_load(scales)

# Dashboards e HTML
p_load(htmlwidgets)
p_load(highcharter)
p_load(leaflet)
p_load(htmltools)
p_load(fontawesome)
p_load(shiny)
p_load(shinythemes)
p_load(png)

# Data wrangling
p_load(collapse)
p_load(here)
p_load(tictoc)
p_load(patchwork)
p_load(janitor)
p_load(glue)

# Próprios
p_load(cid10)
p_load(msrpack)

# Leitura
p_load(openxlsx)
p_load(readxl)
p_load(WriteXLS)
p_load(ggthemes)
p_load(googlesheets4)
p_load(vroom)

# Transformação e análise de dados
p_load(caret)
p_load(zoo)
p_load(tidyverse)
p_load(lubridate)

# Ajustes locais ----------------------------------------------------------

set_key(api_key = "tfgapuFbaa8rSY0QS_dbZj9d8qmdeKiXFHl2L39b-FY") # Api HERE
Sys.setenv(TZ="America/Recife")
options(tz="America/Recife")
Sys.getenv("TZ")
options(scipen = 999999)
Sys.setlocale("LC_TIME", "pt_BR")

p_load(gghighlight)


# Carregamentos iniciais --------------------------------------------------
# 

covid <- read_rds(file = "~/Dropbox/Coding/R/SMS/CoronaApp/bin/covid.rds")
diaria <- read_rds(file = "~/Dropbox/Coding/R/SMS/CoronaApp/bin/diaria_imputada.rds") %>%  
  clean_names()

leito_por_hospital <- covid$leito_por_hospital %>%
  filter(dt >= ymd("2021-02-01") & dt <= ymd("2021-04-30")) %>% 
  pivot_longer(cols =  -dt, names_to = "local", values_to = "leitos")
  
g <- leito_por_hospital %>% 
  ggplot(aes(x = dt, y = leitos, fill  = local, color = local)) +
  geom_point() +
  theme(legend.position = "none")





ocupa_leitos <- function(nome_hospital) {
  uti <- covid$uti %>% 
    filter(dt >= ymd("2021-02-01") & dt <= ymd("2021-04-30")) %>% 
    filter(adulto_ped == "UTI ADULTO") %>% 
    filter(hospital == nome_hospital) %>% 
    select(dt, hospital, leitos, bloqueados, pacientes, covid_susp, 
           covid_positivo, emerg_covid, emerg_n_covid, pac_nao_covid) %>% 
    mutate(
      ocupacao = pacientes / (leitos - bloqueados)
    )
  
  coeficente <-  1 /( diff(range(uti$leitos)) / diff(range(uti$ocupacao)) )
  
  
  
  uti %>% 
    ggplot(aes(x = dt)) + 
    geom_line(aes(y = leitos), color = "red", show.legend = TRUE) + 
    geom_line(aes(y = ocupacao / coeficente)) + 
    scale_y_continuous(
      name = "Quantidade de leitos",
      sec.axis = sec_axis(~.*coeficente, name = "Ocupação", labels = percent)
    ) +
    ggtitle(label = nome_hospital,
            subtitle = "Fonte: Dashboard das Emergências") +
    xlab("Meses de 2021")
  
}


unique(covid$uti$hospital)
ocupa_leitos( "Hospital Mãe de Deus"   )




```

Quantidade de leitos COVID 19 por hospital no período.
Informações detalhadas ao selecionar o gráfico e passar cursor sobre o mesmo.




```{r, fig.height=6}
plotly::ggplotly(g, tooltip = c("local", "leitos", "dt"))
```

```{r}
diaria %>% 
   filter(dt >= ymd("2021-02-01") & dt <= ymd("2021-04-30")) %>% 
  select(dt, leitos, pacientes, covid = covid_susp_confirmado_total, vent_fora_uti) %>% 
  pivot_longer(cols = -c(dt), names_to = "tipo", values_to = "n") %>% 
  ggplot(aes(x = dt, y = n , fill = tipo, color = tipo)) + 
  geom_line() +
  labs(title = "Quantidade de diferentes pacientes e leitos no período", 
       color = "Tipos de leitos/pacientes",
       x = "Meses de 2021", y = "Quantidade absoluta") +
  scale_color_discrete(labels = c("Pacientes COVID", 
                                  "Quantidade total de leitos", 
                                  "Quantidade total de pacientes de UTI", 
                                  "Pacientes em VM fora de UTI")) +
  theme(legend.position = "bottom") +  guides(color=guide_legend(ncol=2))
  
```

