---
title: "Mapas de calor do SAMU"
description: |
  Utilizando os dados de geolocalização das ocorrências do SAMU no ano de 2020 e 2021.
author:
  - name: Márcio Rodrigues 
    url: https://msrodrigues.github.io/sms/
    affiliation: Secretaria Municipal da Saúde de Porto Alegre
    affiliation_url: https://github.com/msrodrigues
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Atendimentos a trauma na cidade

O seguinte mapa é o compilado do total de atendimentos a trauma nos anos de 2020 e 2021 em Porto Alegre.

```{r, warning=FALSE, message=FALSE, include=FALSE}
# Bibliotecas -------------------------------------------------------------
library(pacman)

# Georreferenciamento e mapas
p_load(ggmap)
p_load(sp)
p_load(rgdal)
p_load(hereR)
p_load(geobr)

# Tabelas, Ferramentas estatísticas,
p_load(directlabels)
p_load(esquisse)
p_load(obAnalytics)
p_load(DescTools)
p_load(kableExtra)
p_load(RColorBrewer)
p_load(scales)

# Dashboards e HTML
p_load(htmlwidgets)
p_load(highcharter)
p_load(leaflet)
p_load(htmltools)
p_load(fontawesome)
p_load(shiny)
p_load(shinythemes)
p_load(png)

# Data wrangling
p_load(collapse)
p_load(here)
p_load(tictoc)
p_load(patchwork)
p_load(janitor)
p_load(glue)

# Próprios
p_load(cid10)
p_load(msrpack)

# Leitura
p_load(openxlsx)
p_load(readxl)
p_load(WriteXLS)
p_load(ggthemes)
p_load(googlesheets4)
p_load(vroom)

# Transformação e análise de dados
p_load(caret)
p_load(zoo)
p_load(tidyverse)
p_load(lubridate)

# Ajustes locais ----------------------------------------------------------

set_key(api_key = "tfgapuFbaa8rSY0QS_dbZj9d8qmdeKiXFHl2L39b-FY") # Api HERE
Sys.setenv(TZ="America/Recife")
options(tz="America/Recife")
Sys.getenv("TZ")
options(scipen = 999999)
Sys.setlocale("LC_TIME", "pt_BR")

p_load(leaflet)
p_load(leaflet.extras)

# Carregamentos iniciais --------------------------------------------------
samu <- read_rds(file = "../../../data/samu/bin/samu.rds") %>% 
  mutate(
    lat = lat / 10^(nchar(abs(lat)) - 2),
    long = long / 10^(nchar(abs(long)) - 2)
    
  )
```


```{r, warning=FALSE, message=FALSE, fig.width=19}
samu %>% 
  filter(ano >= 2020) %>% 
  filter(motivo == "SOCORRO") %>% 
  filter(grupo_comp == "TRAUMÁTICO") %>% 
  filter(!is.na(lat) & !is.na(long)) %>% 
  filter(lat < 0 & long < 0) %>%
  leaflet() %>% 
  addTiles(group = "OSM") %>% 
  addProviderTiles("CartoDB", group = "Carto") %>% 
  addProviderTiles("Esri", group = "Esri")  %>%
  
  addLayersControl(baseGroups = c("Carto","OSM","Esri"),
                   position = "topleft") %>% 
  setView(lat = -30.09, lng = -51.21, zoom = 14) %>% 
  addHeatmap(
    lng = ~long, lat = ~lat,
    blur = 12, max = 35, radius = 9, 
  )

```






